---
features:
  - The ``os_ceilometer`` role now includes a facility where you
    can place your own templates in ``/etc/openstack_deploy/ceilometer``
    (by default) and it will be deployed to the target host after being
    interpreted by the template engine. If no file is found there, the
    fallback of the git sourced template is used.
