---
# Copyright 2018, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in ceilometer_developer_constraints %}
      {{ item }}
      {% endfor %}
  when:
    - ceilometer_developer_mode | bool

- name: Retrieve checksum for venv download
  uri:
    url: "{{ ceilometer_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: ceilometer_venv_checksum
  when: ceilometer_venv_download | bool

- name: Attempt venv download
  get_url:
    url: "{{ ceilometer_venv_download_url }}"
    dest: "/var/cache/{{ ceilometer_venv_download_url | basename }}"
    checksum: "sha1:{{ ceilometer_venv_checksum.content | trim }}"
  register: ceilometer_get_venv
  when: ceilometer_venv_download | bool

- name: Remove existing venv
  file:
    path: "{{ ceilometer_bin | dirname }}"
    state: absent
  when: ceilometer_get_venv  is changed

- name: Create ceilometer venv dir
  file:
    path: "{{ ceilometer_bin | dirname }}"
    state: directory
  register: ceilometer_venv_dir
  when: ceilometer_get_venv  is changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ ceilometer_venv_download_url | basename }}"
    dest: "{{ ceilometer_bin | dirname }}"
    copy: "no"
  when: ceilometer_get_venv  is changed
  notify: Restart ceilometer services

- name: Install pip packages
  pip:
    name: "{{ ceilometer_pip_packages }}"
    state: "{{ ceilometer_pip_package_state }}"
    virtualenv: "{{ ceilometer_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ ceilometer_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ ceilometer_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  when: ceilometer_get_venv | failed or ceilometer_get_venv | skipped
  notify: Restart ceilometer services

- name: Remove python from path first (CentOS, openSUSE)
  file:
    path:  "{{ ceilometer_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']
    - ceilometer_get_venv  is changed

# NOTE(odyssey4me):
# We reinitialize the venv to ensure that the right
# version of python is in the venv, but we do not
# want virtualenv to also replace pip, setuptools
# and wheel so we tell it not to.
# We do not use --always-copy for CentOS/SuSE due
# to https://github.com/pypa/virtualenv/issues/565
- name: Update virtualenv path
  shell: |
    find {{ ceilometer_bin }} -name \*.pyc -delete
    sed -si '1s/^.*python.*$/#!{{ ceilometer_bin | replace ('/','\/') }}\/python/' {{ ceilometer_bin }}/*
    virtualenv {{ ceilometer_bin | dirname }} \
        {{ (ansible_pkg_mgr == 'apt') | ternary('--always-copy', '') }} \
        --no-pip \
        --no-setuptools \
        --no-wheel
  when: ceilometer_get_venv  is changed
  tags:
    - skip_ansible_lint

- name: Install optional pip packages
  pip:
    name: "{{ ceilometer_optional_oslomsg_amqp1_pip_packages }}"
    state: "{{ ceilometer_pip_package_state }}"
    virtualenv: "{{ ceilometer_bin | dirname }}"
    virtualenv_site_packages: "no"
  when: ceilometer_oslomsg_amqp1_enabled
  register: install_optional_packages
  until: install_optional_packages is success
  retries: 5
  delay: 2
  notify: Restart ceilometer services

- name: Find the venv's python version
  find:
    paths: "{{ ceilometer_bin | dirname }}/lib/"
    patterns: "python*"
    file_type: directory
    recurse: no
  register: python_venv_details

- name: Set python venvs details
  set_fact:
    venv_python_version: "{{ (python_venv_details.files[0].path | basename) }}"
    venv_python_major_version: "{{ (python_venv_details.files[0].path | basename)[:-2] }}"
    venv_python_lib_folder: "{{ python_venv_details.files[0].path }}"

- name: Search for lib files to link
  shell: >-
    {{ (ansible_pkg_mgr == 'apt') | ternary('dpkg -L ' ~ (ceilometer_packages_to_symlink | join(' ')), 'rpm -ql ' ~ (ceilometer_packages_to_symlink | join(' ')) ) }}
    | egrep '^.*{{ venv_python_major_version }}.*/(site|dist)-packages/.*'
  args:
    warn: no
  changed_when: false
  register: _python_files

- name: Link the python host package files into venv
  file:
    src: "{{ item }}"
    dest: "{{ venv_python_lib_folder }}/site-packages/{{ item | basename }}"
    state: link
    force: yes
  with_items: "{{ _python_files.stdout_lines }}"

- name: Record the venv tag deployed
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: ceilometer
    option: venv_tag
    value: "{{ ceilometer_venv_tag }}"
